config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders 

  resources :line_items do
    put 'decrease', on: :member
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
	<div id="banner">
		<%= image_tag('logo.png') %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
		<div id="side">
			<% if @cart %>
				<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
					<%= render @cart %>
				<% end %>
			<% end %>
			<ul>
				<li><a href="http://www.....">Home</a></li>
				<li><a href="http://www...../faq">Questions</a></li>
				<li><a href="http://www...../news">News</a></li>
				<li><a href="http://www...../contact">Contact</a></li>
			</ul>
			<% if session[:user_id].nil? %>
				<% if User.count.zero? %>
					<%= button_to 'Log in', new_user_path, method: :get %>
				<% else %>
					<%= button_to 'Log in', login_path, method: :get %>
				<% end %>
			<% else %>
			<ul>
				<li><%= link_to 'Orders', orders_path %></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>